// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJHaz-XeEf1vnJWODb9chW5gM2vTS3N34',
    appId: '1:214772217007:web:5d20a74f870eabc988505a',
    messagingSenderId: '214772217007',
    projectId: 'homeo-backend',
    authDomain: 'homeo-backend.firebaseapp.com',
    storageBucket: 'homeo-backend.firebasestorage.app',
    measurementId: 'G-CGMGCPK3QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7qrfwbrIXjNQ5QRRpCIPBf0JWR-8L6yI',
    appId: '1:214772217007:android:6a55d7550b58e51888505a',
    messagingSenderId: '214772217007',
    projectId: 'homeo-backend',
    storageBucket: 'homeo-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmESJbVlNhfkWBK-0Lh4YLJFjUppmP8vs',
    appId: '1:214772217007:ios:eabc1acd2f603b8b88505a',
    messagingSenderId: '214772217007',
    projectId: 'homeo-backend',
    storageBucket: 'homeo-backend.firebasestorage.app',
    iosBundleId: 'com.example.flutterHomeopathyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmESJbVlNhfkWBK-0Lh4YLJFjUppmP8vs',
    appId: '1:214772217007:ios:eabc1acd2f603b8b88505a',
    messagingSenderId: '214772217007',
    projectId: 'homeo-backend',
    storageBucket: 'homeo-backend.firebasestorage.app',
    iosBundleId: 'com.example.flutterHomeopathyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJHaz-XeEf1vnJWODb9chW5gM2vTS3N34',
    appId: '1:214772217007:web:47806d7b21bdee3c88505a',
    messagingSenderId: '214772217007',
    projectId: 'homeo-backend',
    authDomain: 'homeo-backend.firebaseapp.com',
    storageBucket: 'homeo-backend.firebasestorage.app',
    measurementId: 'G-WLN8YGWZ6L',
  );
}
